denzilferreira/aware-client

- aware-core/src/main/java/com/aware/Accelerometer.java
- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/Barometer.java
- aware-core/src/main/java/com/aware/Gravity.java
- aware-core/src/main/java/com/aware/Gyroscope.java
- aware-core/src/main/java/com/aware/Light.java
- aware-core/src/main/java/com/aware/LinearAccelerometer.java
- aware-core/src/main/java/com/aware/Magnetometer.java
- aware-core/src/main/java/com/aware/Proximity.java
- aware-core/src/main/java/com/aware/Rotation.java
- aware-core/src/main/java/com/aware/Temperature.java
- aware-core/src/main/res/xml/aware_preferences.xml
- aware-phone/src/main/java/com/aware/phone/Aware_Client.java
- aware-phone/src/main/res/xml/aware_preferences.xml
As discussed in denzilferreira/aware-client#30.  Only baseline testing on
my device, could use more.
- This avoids recording successive points if the values have not
changed much.  This allows high frequency sampling while also not
generating ridiculous amounts of data (for example when the phone is
not actively moving, for accelerometer).
- The option is present in the UI but there are no default choices to
pick from.  Default value is zero, which should be previous
behavior.
- Option name: threshold_accelerometer, etc.
- For all high-frequency sensors.
> Add threshold_* configuration options.

- aware-core/src/main/java/com/aware/Applications.java
- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/Communication.java
- aware-core/src/main/java/com/aware/Telephony.java
- aware-core/src/main/java/com/aware/utils/Encrypter.java
PR for denzilferreira/aware-client#40 (hashing).  Not ready to be merged yet.
- Any first thoughts?  More comments in the issue.
- Any disadvantage to combining all the hash algorithms into `hashGeneric` ?
- I have gone ahead and replaced all calls to hash to this on.
- Is getSetting(context) supposed to be a fast operation?
- It would be safe to let us internally test some before merging, but I would be interested on your current thoughts for likelihood.
Commit message below:
- Encrypter.hash(): Hash things, taking into account the
"hash_function" and "hash_salt" settings.
- Encrypter.hashPhone(): Hash phone numbers.  Can take extra
procedures for normalization or salting if desired.
New settings:
- "hash_function": ""=SHA-1 (default), "MD5", "SHA-1", "SHA-256",
"SHA-512" (must be these …
> Improve hashing: specify hash functions and salts.

- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/Locations.java
This adds support for geofencing of locations.  Locations are only recorded if within one of the fences, other wise blank values with label=`outofbounds` is recorded.
Here is a sample fence, a circle of radius 700m and a rectangle: `60.185222,24.821330,700 rect,60.171101,24.914507,60.160396,24.821774`
- Should the location sensor record "null" instead of zeros when there is no data?
- Telephony sensor appears to be able to record location, I haven't handled that yet.
I have been testing this, but will continue to do so more.  Appears to work so far.
Commit message:
- location_geofence setting:
Location geofence.  If given and location does NOT fall within,
then do not record location points.
Format: "fence1 fence2 ..." (space separated string)
Circle fence: "lat,lon,radius".  Radius in …
> Add geofencing support to Locations probe.

- aware-core/src/main/java/com/aware/Applications.java
- aware-core/src/main/res/values/strings.xml
This is a simple pull request.  I have observed several people not realizing you can click the notification to go to accessibility settings, so I labeled it as such.
However, does this work on all android versions?
> Accessibility services: clarify instructions for activating

- aware-core/src/main/java/com/aware/utils/DatabaseHelper.java
In `DatabaseHelper.java`, the database location was duplicated in three places.  This puts it in one place using methods.  This has no effect on upstream AWARE, but make it easier for us to modify it if needed (less divergence from upstream).
Commit message:
- No functionality changes.
- This puts all code which opens databases in two methods.
- This will allow less invasive changes in the future.
> DatabaseHelper: abstract out database locator functions.

- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/utils/WebserviceHelper.java
- aware-core/src/main/res/xml/aware_preferences.xml
- aware-phone/src/main/java/com/aware/phone/Aware_Client.java
- aware-phone/src/main/res/xml/aware_preferences.xml
Hi,
I'm not sure if you will want this, but these patches add two variables `webservice_stateless` and `webservice_only`, which if combined will give this the behavior of the iOS app and remove all data once it is uploaded.  This is to user-visible anywhere, so is only activated if you like with a server that supports it.  The people running the study have to be clever enough to know that it does not work with all probes or plugins, and know the implications of not doing a three-phase sync.  I would consider it advanced use.
Note that indentation is wrong in this patch (to minimize the diff).  If you want to accept it, I will fix up the indentation first and then you can take it.
Thanks,
- Richard
Commit message:
- webservice_stateless: don't /create_table: in this case, the server
saves …
> Add some options for webservice uploading

- aware-core/src/main/java/com/aware/utils/StudyUtils.java
- When a study is joined, don't use a notification that needs to be
dismissed, but a toast instead.  Toast content is the same as the
notification content.
> Join study: Change to use toast instead of notification

- aware-core/src/main/res/xml/aware_preferences.xml
- aware-phone/src/main/res/xml/aware_preferences.xml
- There should be no differences in meaning before and after this
change.
- A diff of the two files now shows only the main difference: the
toolbars and icons.
- Future changes can be more easily synced between the files using
diff/patch or a graphical merge tool.
> Reduce diff in aware_preferences.xml between aware-core and aware-phone 

- aware-core/src/main/java/com/aware/utils/StudyUtils.java
This is trying to solve the issue in  #55, using Denzil's suggested fix.  At least it seems to work for me, but it worked before for me anyway so I can't test it well.  Comments?  (Note: toast is still long, it does seem rather long to me, but in my experience many people, after joining, are quite confused about what is going on and the extra 1.5s is useful.)
commit msg:
- Android has a problem with toasts not disappearing in IntentService,
this hopefully fixes is.
> Study joining: fix bug with toasts not destroying

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/utils/WebserviceHelper.java
- aware-core/src/main/res/xml/aware_preferences.xml
- aware-phone/src/main/java/com/aware/phone/Aware_Client.java
- aware-phone/src/main/java/com/aware/phone/ui/Aware_Activity.java
- aware-phone/src/main/res/xml/aware_preferences.xml
Another low-hanging fruit: add an advanced option to not show notification when uploading data.  Also add toast which appears when you click manual upload button.  Also adds my three new webservice options to the `global_settings` hash in `Aware.java` - I think they should have been there before.
commit msg:
- This option surpresses the notification when uploading data.  For
some studies, we shouldn't be so apparent.
- Option name webservice_silent, if "true" then do not show anything,
all other values cause notification to be shown.
- A toast is added when clicking the manual upload button.  This
provides some context to the manual upload button, so that if
silent=true, the user still knows the click worked.
- This is visible in the UI and users can always adjust it, even if we
are in a …
> Add webservice_silent option: don't show notification when uploading

- aware-core/src/main/java/com/aware/utils/StudyUtils.java
- I got a crash when this code was invoked when JOIN_TOAST was null.
This provides safety.
- Perhaps it can get here if StudyUtils class invoked without the
intent, or it fails before JOIN_TOAST is made?  (I'm not sure the root cause)
> Join toast: don't cancel if join_toast is null.

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/utils/SSLManager.java
- aware-core/src/main/java/com/aware/utils/StudyUtils.java
- aware-core/src/main/res/xml/aware_preferences.xml
- aware-phone/src/main/java/com/aware/phone/Aware_Client.java
- aware-phone/src/main/java/com/aware/phone/ui/Aware_QRCode.java
- aware-phone/src/main/res/xml/aware_preferences.xml
This is the start of a commit to make donating usage information optional.  By default it is off, but users can turn it on.  This commit isn't ready for pulling yet, but making the request to get feedback.
To-do:
- Currently, in Aware.java, it sends an intent to get the cert of the server's api.  I should do something about this still.  The comment implies that this is for the use getting plugins, but this now goes to the play store directly, so is it not necessary anymore?  However, presumably it is also necessary for sending the usage information.
- I was going to add the certificate-getting in the AsynchronousPing.  As part of this, I would add another function ensureCertificate or some such, which gets the certificate if it doesn't already exist.  It isn't very secure for certificates …
> Option to donate usage data to AWARE project

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/java/com/aware/utils/StudyUtils.java
This sends some new keys when doing sending usage information or joining a study.  Servers can do what they wish with it.  At least for the usage information, it doesn't exist elsewhere.  I don't know if there is a more canonical location for this information for joining the study, but I don't see it aware_device at least.  Also, this data can be dynamic so maybe it should even be sent each time data is uploaded.
Requesting comments first.
commit msg:
- Include package name, package version name, package version code,
and platform=android.
> When joining studies/sending usage information, include package data.

- aware-core/src/main/java/com/aware/utils/SSLManager.java
- See comments for details, there was a branch that appeared
unimportant, but was necessary as a base case to prevent "else"
handling.
- This logic was used mainly for clarity (two positive conditions,
instead of one positive and one negative), but wasn't documented
enough.
> SSLManager: fix regression in new cert fetching methods

- aware-core/src/main/AndroidManifest.xml
Only the client needs this class, resulting in double ESM notifications.
> - Fix: Remove "exported = true" from QueueESM in the manifest. 

- aware-core/src/main/java/com/aware/WiFi.java
Wait to see if there are issues when/if the IntentService kills the data logging threads.
> Remove timeout for WiFi logging.

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/java/com/aware/utils/DownloadPluginService.java
- aware-core/src/main/java/com/aware/utils/StudyUtils.java
- aware-phone/src/main/java/com/aware/phone/ui/Aware_Join_Study.java
- aware-phone/src/main/java/com/aware/phone/ui/Plugins_Manager.java
This allows hosting your own plugins without putting them to the Play store. The relevant parts of the study url will be used to find the right server.
> Allow passing custom study urls to Plugin Downloader.

- aware-core/src/main/java/com/aware/WiFi.java
Compiling the client using gradlew resulted in the following warning. Changes reflect the compiler's suggestion
```
WiFi.java:84:Error:....
WiFi.java:262: Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing  to .getApplicationContext()  [WifiManagerLeak]
WifiManager wifiManager = (WifiManager) getSystemService(WIFI_SERVICE);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Explanation for issues of type "WifiManagerLeak":
On versions prior to Android N (24), initializing the WifiManager via
Context#getSystemService can cause a memory leak if the context is not the
application context. Change context.getSystemService(...) to
context.getApplicationContext().getSystemService(...).
```
> - Fix: Memory leak in Wifi service

- aware-core/src/main/res/xml/aware_preferences.xml
Hi,
This clarifies some of the location wordings.  Last year I spent several hours trying to figure out why locations wasn't giving any values before I found out that accuracy meant a distance threshold for sending new values.  This came up today again, so I made this quick patch.
======
- The frequency/accuracy do not mean exactly what they imply.  They
are sent to Android and it tries to make a clever schedule giving
updates.
- Frequency: location updates are given no more frequently than the
given value.  It can be less if Android sees no reason to update
again (see accuracy below).
- Accuracy: if the device has not moved more than this amount, then do
not give location updates.
- There are changes to functionality of Aware, only explanation in UI.
> aware_preferences.xml: Location: clarify location descriptions.

- aware-core/src/main/java/com/aware/utils/WebserviceHelper.java
Hi,
This goes along with "webservice_remove_data", which makes Aware clear all data from the tables.  Aware was changed to use the last row of aware_studies to view study info.  This change prevents clearing that table (it only keeps the last line), and could be extended to others too.  However, I don't know if this is the best way to do this.  It hard-codes table names into another file instead of using the provider.  Maybe there's a better way that can extend to other plugins?
I don't know if others want to use "webservice_remove_data", if not then I'm fine with maintaining this patch in our own branch.
====
Don't clear aware_studies table when webservice_remove_data=true
- The aware_studies table is special, because it is needed in order to
get the study info.  If it is cleared, you …
> Don't clear aware_studies table when webservice_remove_data=true

- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/Locations.java
- aware-core/src/main/res/xml/aware_preferences.xml
This adds a new configuration option "location_save_all".  When this is set, every single location that android produces gets saved to the log, even if it is within the expiration time, is less accurate, etc.  This gives the most complete picture for future analysis, even if it is slightly less useful for real-time analysis by other apps.
Note some of the code was split into another function save_location, and the diff below is a bit confusing because of this.
This is *probably* safe to merge, but I am still testing it - I will give final confirmation in a day or two.
> Location save all

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/Locations.java
- aware-core/src/main/res/xml/aware_preferences.xml
Note: this depends (is derived from) on PR #164 (location_save_all), don't merge until that is done... and until that's done, diff will be bad.  
Note: don't merge yet, still being tested!
This adds support for the passive location provider, which doesn't turn any sensors on, but will use locations which are requested by other applications.  The semantics and config options could still use some thinking.
This would solve #168.
Thanks,
- Richard
-----
- The passive location provider does not turn on GPS or triangulation,
but will give you the locations if any other apps decide to turn
these sensors on.
- Currently you don't set the frequency/movement threshold of this
sensor, and it registers the listener with a period of 60 seconds.
Actual frequency will be determined by whatever app is …
> Passive location

- aware-core/src/main/res/values/arrays.xml
- aware-core/src/main/res/xml/aware_preferences.xml
Hi,
This adjusts the default selectable frequency values.  It adds one thing more slower to all sensors, and for barometer, light, temperature, and proximity provides some much lower values also.  This is most useful with the enforce_frequency PR, since Android can still give points more frequently than what is requested, so just setting a lower value doesn't directly reduce the data.
It would be best to think about what values are most useful before merging.  FYI: we also use a medical-grade wrist-worn activity tracker, and this collects a single accelerometer data point every 30 seconds.  So slower values are not entirely unheard of.
> Low frequency sensor values

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/java/com/aware/utils/SSLManager.java
- aware-core/src/main/java/com/aware/utils/StudyUtils.java
- aware-phone/src/main/java/com/aware/phone/Aware_Client.java
- aware-phone/src/main/java/com/aware/phone/ui/Aware_QRCode.java
Hi,
Some things about SSL handling.
- in `handleUrl`, don't run `getCertificateExpiration` twice in a row.  Cache the result.  This accesses the network so better to do this.
- Change some occurrences of `downloadCertificate` to `handleUrl`.  I did this in a previous PR, but it seems to have been lost.  the purpose is that `handleUrl` always gets the full `webservice_server` url (including any query arguments, if they are any) and handles whatever our cert updating policy is.  The check using `getCertificateExpiration` is in here, for example.  This can use the `key_strategy` option (as for as I know, I'm the only one that does this...)  By default, with no other options, it calls `downloadCertificate` (after the new expiration check), which was the previous default behavior.
- Note: I …
> Ssl handling

- aware-core/src/main/java/com/aware/utils/DatabaseHelper.java
- aware-core/src/main/java/com/aware/utils/SSLManager.java
- aware-core/src/main/res/values/bools.xml
In this PR, we add a resources option (bools.xml) which can allow data to be stored in internal storage, instead of external public.  This is in parallel to the recent "standalone" option, but works in less places.  It would only be used for specific projects with standalone apps. 
- This, like the `standalone` option, allows one to change where the
data is stored.  This puts data into internal storage.
- This should only be used if you know what you are doing.  It is
hardcoded to off.  Data won't be accessible to you, so debugging is
harder.
- This won't work with plugins.  There are probable other corner
cases, too.
- You can access the data if you backup the app.  Clearly this is only
for debugging.  For a hint at extracting the backup, see
https://android.stackexchange.com/a/78183
> Add option for storing databases in internal storage (default disabled)

- aware-core/src/main/java/com/aware/Aware_Preferences.java
- aware-core/src/main/java/com/aware/Bluetooth.java
- aware-core/src/main/java/com/aware/WiFi.java
- aware-core/src/main/java/com/aware/utils/Encrypter.java
I had previously made a more advanced method of hashing phone numbers, which could have different policies depending on how linkable or unlinkable you wanted things.
Now, I also need to hash network MACs/names, so instead of making more special cases, I introduced the concept of a hash program.  In the most basic sense, it just does a hash.  You can also specify normalization, salting (both with fixed seeds and with the device ID), taking the last N digits of a number, etc.  It may be a bit overkill, but I thought it better than copying and pasting and special-casing each thing that needs hashing.
Phone and default hashes run the same as before.  Now there are functions hashMac and hashSsid, which do what they say.  They default to returning the cleartext.  Config options are unchanged …
> Add more advanced hashing options (phone, MACs, network names)

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/res/values/integers.xml
The study check and keepalive were hardcoded in the application.  This splits them into an integer resources file.  Useful for me because it makes it easier to keep my own branch's patches clean.
====
- default_study_check_interval_min
- keep_alive_interval_min
- These are hardcoded and would only be changed in specific branches
> Split some hardcoded options into a resources integers.xml file

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/res/values/strings.xml
Splitting out some of the new notification texts into strings.xml.  Again, this is useful to translate in my own branch for a study.  Perhaps I'll do more of these in the near future.
Would you be interested in a configuration option for a persistent notification?  I'm guessing this is to handle the latest API which is more aggressive in power saving?
> Put foreground notification text into res/values/strings.xml

- aware-core/src/main/java/com/aware/Aware.java
- the study URL may have query parameters, while these are stripped
when it is converted to a webservice URL.  This makes the "LIKE" no
longer match.  This patch allows any query arguments (or extension) to the
webservice URL.
(yes, there's an extra addition: I assume clarity is more important than conciseness)
> isStudy: fix problem with advanced study URLs

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/java/com/aware/utils/Scheduler.java
- aware-core/src/main/res/values/integers.xml
- New integer resource: alarm_wakeup_interval_min.  Interval that
schedule should tick.
- This allows researchers to trade off between battery usage and
promptness of scheduler updates.  If it's increased, it may also
encourage Android to put the app in a better battery usage class
and treat it less badly
- Default remains the same: wakeup every minute.
> Make scheduler wakeup interval configurable via resources

- aware-core/src/main/java/com/aware/Aware.java
- aware-core/src/main/res/values/integers.xml
This is the missing part of #217 I was talking about.  It lets you reduce the scheduler ticker interval to even less than 1 minute if you want to.  I found it useful because if you are only doing scheduler stuff, it can reduce the amount of processor and probably get better treatment from Android.  By default, no change from previous behavior.
----
- Android always ticks at 1-minute intervals (supposedly, but it can
be anything).  This provides a switch to run the scheduler less
often than this if you want.
> Make SchedulerTicker effective frequency configurable

- aware-core/src/main/java/com/aware/Aware.java
Hi,
I just remembered to make this PR about schedulers.  Aware should be able to update schedules from the study_check, but there were several things I encountered:
1) First, the necessary sync code only ran when it was not standalone, but `com.aware.phone` wasn't in that category.  Should this get the standard exception?
2) Second, the schedules were only updated when some other config changed.  This wasn't good in our case.
But don't merge yet!  This patch works and was tested in our latest study, but has certain assumptions.  If schedules are updated every time, the same schedule ID will be found and it will simply update the row in the database (this is what we used (actually server-side random questionnaires)).  But, if there are random questionnaires, then:
a) inserted at new random …
> Schedule update

- aware-core/src/main/java/com/aware/utils/Scheduler.java
Hi,
Another old branch, rebased to current development.  See the commit messages for most of the description.
Several changes that require conscious choices:
- Random number generators are now seeded per (day,schedule), so that times are reproducible.  This was important for me, so that if config changes, schedules could be deleted and recreated without changing the scheduling pattern.
- Related to above, when randoms are scheduled, consider the whole day.  If a time was in the past, ignore it instead of compressing all randoms into the remaining time.
- Related to the two above: all users get randoms at the same time.  This was a conscious choice, but can easily be changed by seeding by device_id also.  I can add an option for this if you'd like.
All of these patches are together in one …
> Scheduler: various fixes and improvements.

- aware-core/src/main/java/com/aware/Bluetooth.java
- Uses callbacks to start and stop BLE scanning.
- Scan BLE devices for 3 seconds
> BLE now follows the scan frequency

- aware-core/src/main/java/com/aware/syncadapters/AwareSyncAdapter.java
Hi,
The transition to sync adapters made the webservice_simple flag (the one that always uploads all data, does not call /latest) not work, because `latest` was null.  This fixes it by setting it to `[]`, indicating "no most recent data" which causes Aware to upload all data, which is the desired behavior.
- Richard
> webservice_simple: fix for transition to sync adapters

- aware-core/src/main/java/com/aware/syncadapters/AwareSyncAdapter.java
- There was an extra space in the string used for the last timestamp query
- Improved debugging of the core by allowing us to know how many records are pending to sync for this sync batch.
> Fix serverless sync

- aware-core/src/main/java/com/aware/utils/Aware_Sensor.java
when the old certificate file is missing, SSLManager is called to re-download the certificate (on the main thread) that causes a network issue. This is a first attempt to solve that.
> Place the call to SSLManager (in Aware_Sensor) in AsyncTask

- aware-core/src/main/java/com/aware/utils/Scheduler.java
The SQL query selected the whole 'last_triggered' column because the second part of the AND operator was not wrapped within brackets. Now it only selects the desired row.
> Fixed SQL query when updating schedules 'last_triggered' value
